### PR TITLE
feat: add DashScopeChatModel call and stream observability

### PR DESCRIPTION
**Pull request by Cirilla-zmh**
Add DashScopeChatModel call and stream observability so that we can trace and generate metrics for `DashScopeChatModel`.

### CODE REVIEW

**Comment by robinyeeh** [comment]
LGTM

**Review by chickenlj — APPROVED** [review]
LGTM.

**Comment by liugddx** [comment]
Why implement it here instead of contribute to spring ai?

**Comment by Cirilla-zmh** [comment]
> Why implement it here instead of contribute to spring ai?

Instrumentation should be integrated with the instrumented components, so I can only provide an implementation here.
If you are wondering why the DashScope ChatModel is not implemented in Spring AI, perhaps other maintainers can provide more details.
cc @chickenlj @robinyeeh

**Pull request merged**
